const PageRoutes = {
    AddUser: "/users/add",
    AddLocation: "/locations/add",
    AddInventoryCategory: "/inventory-categories/add",
    InventoryCategory: "/inventory-categories",
    EditInventoryCategory: "/inventory-categories/edit/:id",
    InventoryRecords: "/inventory",
    InventoryHistory: "/inventory-history",
    AddInventoryHistory: "/inventory-history/add",
    AddInventory: "/inventory/add",
    UpdateInventory: "/inventory/update/:id",
    Projects: "/projects",
    AddProject: "/projects/add",
    EditProject: "/projects/update/:id",
    ProjectInventory: "/project-inventory",
    AddProjectInventory: "/project-inventory/add",
    EditProjectInventory: "/project-inventory/update/:id",
    Tasks: "/tasks",
    AddTask: "/tasks/add",
    EditTask: "/tasks/edit-task/:id",
    TaskInventory: "/task-inventory",
    AddTaskInventory: "/task-inventory/add",
    EditTaskInventory: "/task-inventory/edit/:id",
}

export default PageRoutes;