const PageRoutes = {
    AddUser: "/users/add",
    AddLocation: "/locations/add",
    AddInventoryCategory: "/inventory-categories/add",
    InventoryCategory: "/inventory-categories",
    EditInventoryCategory: "/inventory-categories/edit/:id",
    InventoryRecords: "/inventory-categories/inventories/:id",
    InventoryToTask: "/projects/tasks/task-inventories/:id/:taskId",
    AddInventoryToTask: "/projects/tasks/task-inventories/add/:id/:taskId",
    AddInventory: "/inventory-categories/inventories/add/:id",
    InventoryDetails: "/projects/details/task-details/inventory-details",
    UpdateInventory: "/projects/inventories/update/:id/:categoryId",
    Projects: "/projects",
    AddProject: "/projects/add",
    EditProject: "/projects/update/:id",
    ProjectInventory: "/projects/project-inventory/:id",
    AddProjectInventory: "/projects/project-inventory/add/:id",
    EditProjectInventory: "/project-inventory/update/:id",
    Tasks: "/projects/tasks/:id",
    TaskDetails: "/projects/details/task-details/:id/:taskId",
    AddTask: "/projects/tasks/add/:id",
    EditTask: "/projects/details/task-details/edit/:projectId/:taskId",
    TaskInventory: "/task-inventory",
    AddTaskInventory: "/projects/tasks/task-inventory/add",
    EditTaskInventory: "/task-inventory/edit/:id",

    ProjectDetails: "/projects/details/:id",
}

export default PageRoutes;